spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: epkxbscp
    url: jdbc:mysql://8.130.72.17:3306/pan_share?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 8.130.72.17
    port: 6379
    database: 1