spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: hjs
    url: jdbc:mysql://localhost:3306/pan_share?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
